spring:
  application:
    name: demo-app

  # Database Configuration
  datasource:
    url: jdbc:postgresql://postgres:5432/myapp
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
    driver-class-name: org.postgresql.Driver

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Redis Configuration
  redis:
    host: redis
    port: 6379
    password:

  # Elasticsearch Configuration
  elasticsearch:
    uris: http://elasticsearch:9200
    username: elastic
    password: elastic

server:
  port: 8080
  servlet:
    context-path: /api

# JWT Configuration
jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000 # 24 hours

# OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
  file:
    name: /var/log/application.log
  level:
    root: INFO
    com.example.demoapp: DEBUG
    org.springframework.web: INFO