apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: demo-app
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  ELASTICSEARCH_USERNAME: ZWxhc3RpYw==  # elastic
  ELASTICSEARCH_PASSWORD: ZWxhc3RpYw==  # elastic
  JWT_SECRET: eW91ci0yNTYtYml0LXNlY3JldA==  # your-256-bit-secret